### ISSUE TITLE
Input boxes small using KiCad 7.0

### ISSUE THREAD

**Issue by frankplow** [weirdgyn/viastitching#20]
When using KiCad 7.0, the input boxes are unusably small:
<img width="344" alt="Screenshot 2023-03-22 at 12 55 31" src="https://user-images.githubusercontent.com/6375868/226911000-5fba9939-d33f-405c-9121-968b484b9f40.png">

This is similar to the resolved [KiCad issue #13866](https://gitlab.com/kicad/code/kicad/-/issues/13866).

KiCad version info:
```
Application: KiCad PCB Editor arm64 on arm64

Version: 7.0.1-0, release build

Libraries:
	wxWidgets 3.2.2
	FreeType 2.12.1
	HarfBuzz 5.3.1
	FontConfig 2.14.0
	libcurl/7.86.0 SecureTransport (LibreSSL/3.3.6) zlib/1.2.11 nghttp2/1.47.0

Platform: macOS Ventura Version 13.2.1 (Build 22D68), 64 bit, Little endian, wxMac

Build Info:
	Date: Mar 11 2023 12:11:29
	wxWidgets: 3.2.2 (wchar_t,wx containers)
	Boost: 1.80.0
	OCC: 7.6.3
	Curl: 7.77.0
	ngspice: 38
	Compiler: Clang 13.0.0 with C++ ABI 1002

Build settings:
	KICAD_SPICE=ON
```

**Comment by weirdgyn** [comment]
Fixed with commit #534eef6
