### ISSUE TITLE
'pcbnew' has no attribute `BOARD_GetStandardLayerName`

### ISSUE THREAD

**Issue by samangh** [weirdgyn/viastitching#22]
Hi,

Thanks for your work. I'm trying to use the plugin with the latest version of KiCAD. Howerver, I get the error bnelow as a soon as select this plugin from the "External Plugs" menu.

![image](https://github.com/weirdgyn/viastitching/assets/6358351/fe7b0fd6-a30f-4ce6-a5a5-ecbad05f795b)

**Comment by weirdgyn** [comment]
Fixed with commit 5eceeecc6ef6bf7a2934c2ff985af7e0ecae9803 .

**Comment by samangh** [comment]
Thank you @weirdgyn!
