### ISSUE TITLE
Exception on python action plugin code

### ISSUE THREAD

**Issue by guillemgracia** [weirdgyn/viastitching#3]
Hi,

I got an error when trying to use this plugin on Kicad 6 on Windows 11.  I've installed the plugin in the scripting\plugins folder.

![image](https://user-images.githubusercontent.com/33161309/157486617-a1adae4c-170c-4909-8f53-109a6ce6e699.png)

This hapened to me when trying it in a new blank pcbnew window.

thanks for the plugin btw!

**Comment by weirdgyn** [comment]
You need to set default via size and drill in the board setup. I added a warning dialog anyway.
