### ISSUE TITLE
'NoneType' object is not callable error on Kicad 6

### ISSUE THREAD

**Issue by guillemgracia** [weirdgyn/viastitching#4]
Hi weirdgyn, 

I've tried to use your plugin in Kicad 6 on Windows and this error appears every time I try to open the pluggin when I first open the layout of my pcb.

![image](https://user-images.githubusercontent.com/33161309/158355263-23d37a4e-deaa-4976-a821-1fe23fede8f9.png)

Thanks for your work!

**Comment by weirdgyn** [comment]
I should be fixed by merging pull request #5 .
